### ISSUE TITLE
Plugin fails when a classifier has been configured with maven-war-plugin

### ISSUE THREAD

**Issue by michael-o** [khmarbaise/multienv-maven-plugin#15]
I have configured the following in my `pom.xml`:

```
<plugin>
  <artifactId>maven-war-plugin</artifactId>
  <configuration>
    <classifier>localdev</classifier>
  </configuration>
</plugin>
```

The reason is that the base war is solely used to develop in Eclipse, it is not suitable for deployment. This is actually build with your plugin. Running `mvn clean package` gives me:

```
[INFO] --- multienv-maven-plugin:0.3.0-SNAPSHOT:environment (remote-war) @ services-webapp ---
[INFO]
[INFO] We have found 3 environments.
[INFO] We have the following environments: iecmig,prod,test
[INFO]
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 9 resources
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Services Web Application Parent .................... SUCCESS [  0.952 s]
[INFO] Services Web Application: Local Development ........ FAILURE [  8.505 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.618 s
[INFO] Finished at: 2016-10-14T11:14:27+02:00
[INFO] Final Memory: 45M/365M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.soebes.maven.plugins:multienv-maven-plugin:0.3.0-SNAPSHOT:environ
ment (remote-war) on project services-webapp: Error unpacking file [...services-webapp\target\classes] to [...services-webapp\target\multienv-maven-plugin-unpack]: The source must not be a directory. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.soebes.maven.plug
ins:multienv-maven-plugin:0.3.0-SNAPSHOT:environment (remote-war) on project tedab-services-webapp-l
ocaldev: Error unpacking file [...services-webapp\target\classes] to [...services-webapp\target\multienv-maven-plugin-unpack]
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error unpacking file [...services-webapp\target\classes] to [...services-webapp\target\multienv-maven-plugin-unpack]
        at com.soebes.maven.plugins.multienv.EnvironmentMojo.unarchiveFile(EnvironmentMojo.java:119)

        at com.soebes.maven.plugins.multienv.EnvironmentMojo.execute(EnvironmentMojo.java:69)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: org.codehaus.plexus.archiver.ArchiverException: The source must not be a directory.
        at org.codehaus.plexus.archiver.AbstractUnArchiver.validate(AbstractUnArchiver.java:191)
        at org.codehaus.plexus.archiver.AbstractUnArchiver.extract(AbstractUnArchiver.java:132)
        at com.soebes.maven.plugins.multienv.EnvironmentMojo.unarchiveFile(EnvironmentMojo.java:114)

        ... 23 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :services-webapp
```

It seems like this plugin in unware of the chosen classifier on the WAR plugin.

**Comment by DmytriE** [comment]
I know this is an old thread but I am experiencing a similar issue.  My builds will not work when I have the classifier defined.  However, if I comment it out it builds.  The classifier is necessary for our building process.  If anyone is experiencing this issue currently or has some suggestions as to what maybe going on I am open to trying it.  I am running maven-war-plugin v. 3.2.0.  Thanks.
